### ISSUE TITLE
cameraの内部パラメータから計算した水平画角が設定と違う気がする

### ISSUE THREAD

**Issue by ishiguroJSK** [start-jsk/rtmros_choreonoid#217]
あまり急ぎではないですが，choreonoidからROSに吐き出しているカメラ画像の内部パラメータがおかしい気がしています．
rtmros_choreonoid/jvrc_models/JAXON_JVRC/JAXON_JVRCmain.wrlの中では画角が90°と設定されていますが，
```
DEF HEAD_LEFT_CAMERA VisionSensor {
  name "LEFT_CAMERA"
  translation 0.1005 0.035 0.05425
  rotation 0.57735026919 -0.57735026919 -0.57735026919 2.094395102393
  type "COLOR_DEPTH"
  frontClipDistance 0.05
  width 640
  height 480
  frameRate 15
  fieldOfView 1.5708
  sensorId 0
}
```
一方`rostopic echo /multisense_local/left/camera_info`では
```
---
header: 
  seq: 429
  stamp: 
    secs: 29
    nsecs:   1000000
  frame_id: left_camera_optical_frame
height: 480
width: 640
distortion_model: plumb_bob
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [240.0, 0.0, 319.5, 0.0, 240.0, 239.5, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [240.0, 0.0, 319.5, 0.0, 0.0, 240.0, 239.5, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
となっており，640x480でfx=fy=240なので(fx=fyなのもすでに怪しい)，
水直画角は theta_y / 2 = arctan( (高h/2) / fy ) によるとtheta_y = 90°になるのですが，
ROSに出ているfxを信じると，水平画角 theta_x / 2 = arctan( (幅w/2) / fx ) がtheta_x = 106°になってしまっています．
RTM側で吐き出されているカメラパラメータを読めないかと
`rtprint localhost:15005/"JAXON_RED(Robot)0.rtc":HEAD_LEFT_CAMERA`
などやろうと思いましたが，
```
rtprint: Warning: failed to import module Img
rtprint: Type not found: TimedCameraImage
```
となって表示されませんでした．
他に辿るためのコマンドや心当たりのあるソースファイル等ありますでしょうか？
