### ISSUE TITLE
16.04で動かすためのTIPS

### ISSUE THREAD

**Issue by ishiguroJSK** [start-jsk/rtmros_choreonoid#275]
オススメ2018verはこんな感じですかね？
以下の~/catkin_ws/tutorial/src/.rosinstallで，
```
- git:
    local-name: hrpsys
    uri: https://github.com/fkanehiro/hrpsys-base.git
- git:
    local-name: openhrp3
    uri: https://github.com/fkanehiro/openhrp3.git
- git:
    local-name: rtm-ros-robotics/rtmros_choreonoid
    uri: https://github.com/start-jsk/rtmros_choreonoid.git
- git:
    local-name: rtm-ros-robotics/rtmros_common
    uri: https://github.com/start-jsk/rtmros_common.git
- git:
    local-name: rtm-ros-robotics/rtmros_hrp2
    uri: https://github.com/start-jsk/rtmros_hrp2.git
- git:
    local-name: rtm-ros-robotics/rtmros_tutorials
    uri: https://github.com/start-jsk/rtmros_tutorials.git
- git:
    local-name: trans_system
    uri: https://github.com/jsk-ros-pkg/trans_system.git
- hg:
    local-name: multisense
    uri: https://bitbucket.org/crl/multisense_ros
    version: 3.4.9
- git:
    local-name: openrtm_aist
    uri: http://github.com/tork-a/openrtm_aist-release
- git:
    local-name: openrtm_aist_python
    uri: http://github.com/tork-a/openrtm_aist_python-release
- git:
    local-name: rtctree
    uri: http://github.com/tork-a/rtctree-release
- git:
    local-name: rtshell
    uri: http://github.com/tork-a/rtshell-release
- git:
    local-name: rtsprofile
    uri: http://github.com/tork-a/rtsprofile-release
```
```
cd ~/catkin_ws/tutorial/src
wstool update
cd ../
rosdep install -v -r --from-paths src --ignore-src -y
sudo apt-get purge ros-kinetic-hrpsys* ros-kinetic-openrtm* openrtm*
catkin b -c
```
```
(.bashrcに以下追記)
export CNOID_INSTALL_DIR=/usr/local/choreonoid
export CNOID_RTM_DIR=~/catkin_ws/tutorial/devel
export PKG_CONFIG_PATH=${CNOID_INSTALL_DIR}/lib/pkgconfig:$PKG_CONFIG_PATH
export PATH=${CNOID_INSTALL_DIR}/bin:$PATH
```
```
cd
sudo apt-get install libyaml-dev
git clone https://github.com/s-nakaoka/choreonoid.git
cd choreonoid
misc/script/install-requisites-ubuntu-16.04.sh
mkdir build
cd build
## not use python3, and not use pybind11 for backward compatibility (python3 pybind11に関するオプション消えてる気もする)
cmake .. -DCMAKE_INSTALL_PREFIX=${CNOID_INSTALL_DIR} -DOPENRTM_DIR=${CNOID_RTM_DIR} -DENABLE_INSTALL_RPATH=ON -DENABLE_CORBA=ON -DBUILD_CORBA_PLUGIN=ON -DBUILD_OPENRTM_PLUGIN=ON -DBUILD_HELLO_WORLD_SAMPLE=ON -DBUILD_SPRING_MODEL_SAMPLE=ON -DUSE_PYTHON3=OFF -DUSE_PYBIND11=OFF
make -j8
sudo make install
```
```
pkill -9 choreonoid; rtmlaunch hrpsys_choreonoid_tutorials jaxon_red_choreonoid.launch USE_VISION:=False
```
からの
```
ipython -i `rospack find hrpsys_choreonoid_tutorials`/scripts/jaxon_red_setup.py "JAXON_RED(Robot)0"
hcf.abc_svc.goPos(1,0,0)
```
か
```
roseus `rospack find hrpsys_ros_bridge_tutorials`/euslisp/jaxon_red-interface.l
(jaxon_red-init)
send *ri* :go-pos 1 0 0
```
で実行確認

> choreonoid本体のcmake時に
> `export CNOID_RTM_DIR=${HOME}/ros/indigo_parent/devel`
> を
> `export CNOID_RTM_DIR=/opt/ros/kinetic`
> に読み替えて，
> （この設定もしないとrtlsとかでエラーが出る気がする
> ```
> $ sudo vi /etc/omniORB.cfg
> giopMaxMsgSize = 209715200     ＃ 200MB に設定
> ```
> ）
> 以下の.rosinstallで最小構成のワークスペースを作って，
> ```
> - git:
>     local-name: hrpsys
>     uri: https://github.com/fkanehiro/hrpsys-base.git
> - git:
>     local-name: openhrp3
>     uri: https://github.com/fkanehiro/openhrp3.git
> - git:
>     local-name: rtm-ros-robotics/rtmros_choreonoid
>     uri: https://github.com/start-jsk/rtmros_choreonoid.git
> - git:
>     local-name: rtm-ros-robotics/rtmros_common
>     uri: https://github.com/start-jsk/rtmros_common.git
> - git:
>     local-name: rtm-ros-robotics/rtmros_hrp2
>     uri: https://github.com/start-jsk/rtmros_hrp2.git
> - git:
>     local-name: rtm-ros-robotics/rtmros_tutorials
>     uri: https://github.com/start-jsk/rtmros_tutorials.git
> - git:
>     local-name: trans_system
>     uri: https://github.com/jsk-ros-pkg/trans_system.git
> - hg:
>     local-name: multisense
>     uri: https://bitbucket.org/crl/multisense_ros
>     version: 3.4.9
> ```
> ○○ws/以下で`rosdep install -v -r --from-paths src --ignore-src -y`して
> 
> `catkin b -c`でビルドする(gazebo関係がエラー出るけどそれはそれとして，)
> 最近hrpsys_choreonoidのビルドで`TimedRobotState2`周りでエラーが出る気もするので
> (古いaptのhrpsysのidl見に行ってる気がする．ros-kinetic-hrpsys消すとそれはそれでhrpsys/idl/Img.hhがないとかエラーが出る)，
> ```
> sudo mv /opt/ros/kinetic/include/hrpsys/idl/RobotHardwareService.hh /opt/ros/kinetic/include/hrpsys/idl/RobotHardwareService.hh.org
> sudo cp ~/○○ws/devel/include/hrpsys/idl/RobotHardwareService.hh /opt/ros/kinetic/include/hrpsys/idl/
> ```
> とかしちゃうと一応ビルドが通って動く．
> ちゃんと直したほうがいい気もする．
