### ISSUE TITLE
eusモデルをchoreonoidに出現させる方法はありますか

### ISSUE THREAD

**Issue by Naoki-Hiraoka** [start-jsk/rtmros_choreonoid#331]
https://github.com/euslisp/EusLisp/tree/master/models にあるeusモデルをchoreonoidに出現させる方法はありますか?

gazeboにおける[eusurdf](https://github.com/jsk-ros-pkg/jsk_model_tools/tree/master/eusurdf)のようにして，
eusモデルをwrlに，sceneをyamlに変換するとよいのだと思うのですが，これらを行うことが可能なコードはどこかにありますでしょうか．

**Comment by Naoki-Hiraoka** [comment]
https://github.com/fkanehiro/simtrans
を使用するとurdfからwrlが生成できそうなので，
[eusurdf](https://github.com/jsk-ros-pkg/jsk_model_tools/tree/master/eusurdf)で生成されたhttps://github.com/euslisp/EusLisp/tree/master/models のurdfをwrlに変換するのが早いでしょうか

**Comment by YoheiKakiuchi** [comment]
> https://github.com/fkanehiro/simtransを使用するとurdfからwrlが生成できそうなので，
> eusurdfで生成されたhttps://github.com/euslisp/EusLisp/tree/master/models のurdfをwrlに変換するのが早いでしょうか

現状ではそれが一番コード書く量が少ないだろうと思います

**Comment by Naoki-Hiraoka** [comment]
ありがとうございます．

**Comment by YoheiKakiuchi** [comment]
モデルはwrlじゃなくてbody(https://choreonoid.org/ja/manuals/latest/handling-models/bodymodel.html)になるかな？

**Comment by Naoki-Hiraoka** [comment]
```
simtrans -i room73b2-foldable-desk/model.urdf -o /tmp/file.wrl
```
として，
.yamlファイルに
```
obj2:                                                                                                                                                                            
  name: 'OBJ'                                                                                                                                                                    
  file: '/tmp/file.wrl'                                                                                                                                                          
  translation: [1, 0, 0]                                                                                                                                                         
  rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
```
と書いてロードしたところ，
物体がchoreonoid上に出現しましたが，
マウスでドラッグしても動かない,ロボットがcollision検出せずにすり抜けるなど，うまく動いていません．
![Screenshot from 2020-05-19 18-37-33](https://user-images.githubusercontent.com/32383525/82311170-4f56fd80-9a00-11ea-9c0f-5dce1d3b2b6f.png)

bodyファイルとして必要なパラメータが足りていないのか，設定を見落としているのか，確認します．
