### ISSUE TITLE
send *ri* :wait-interpolationが帰ってこない

### ISSUE THREAD

**Issue by YuOhara** [start-jsk/rtmros_choreonoid#50]
目標関節角にchoreonoid及びrvizでは送られているように見えますが、だいぶ待たないと帰ってこないです

**Comment by k-okada** [comment]
joint trajectory action の goal が帰ってきているか見てみて下さい．

--
◉ Kei Okada


2015-09-09 20:47 GMT+09:00 Yu Ohara <notifications@github.com>:

**Comment by YuOhara** [comment]
かなり遅いですが
 /fullbody_controller/joint_trajectory_action/result
は帰ってきていて、そのだんかいでwait-interpolationを抜けています。

**Comment by YuOhara** [comment]
```
header: 
  seq: 9
  stamp: 
    secs: 1497
    nsecs: 793000000
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1482
      nsecs: 136000000
    id: /default_robot_interface_1441798677619176060_4449_fullbody_controller/joint_trajectory_action_9
  status: 3
  text: ''
result: 
```
